// Generated by CoffeeScript 1.4.0
"use strict";

var AppController;

AppController = function($scope, keyUpService, app) {
  return $scope.keyup = function($event) {
    return keyUpService.keyup($event);
  };
};

AppController.$inject = ['$scope', 'keyUpService', 'appService'];
