// Generated by CoffeeScript 1.4.0
"use strict";

angular.module('myApp', ['myApp.filters', 'myApp.services', 'myApp.directives', 'ui', 'ui.bootstrap', '$strap.directives']).config([
  '$routeProvider', '$dialogProvider', function($routeProvider, $dialogProvider) {
    $routeProvider.when('/login', {
      templateUrl: 'html/login.html',
      controller: LoginController
    });
    $routeProvider.when('/board', {
      templateUrl: 'html/board.html',
      controller: BoardController,
      resolve: {
        auth: function(appService) {
          return appService.authenticate();
        }
      }
    });
    return $routeProvider.otherwise({
      redirectTo: '/board'
    });
  }
]);
