// Generated by CoffeeScript 1.4.0
"use strict";

angular.module("myApp.directives", []).directive("contenteditable", function() {
  return {
    require: 'ngModel',
    link: function(scope, element, attrs, ngModel) {
      element.bind('blur', function() {
        return scope.$apply(function() {
          return ngModel.$setViewValue(element.html());
        });
      });
      ngModel.$render = function() {
        return element.html(ngModel.$viewValue);
      };
      return $(document).on('keypress', '[contenteditable]', function(event) {
        return event.which !== 13;
      });
    }
  };
});

angular.module("myApp.directives").directive("ngGravatar", function() {
  return {
    replace: true,
    link: function(scope, element, attrs) {
      return attrs.$observe('ngGravatar', function(email) {
        var hash;
        hash = $.md5(email);
        return element.append("<img src='http://www.gravatar.com/avatar/" + hash + "?s=32'>");
      });
    }
  };
});
